spring:
  application:
    name: cursos-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cursosdb
    username: cursos
    password: cursos
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Deixa o Flyway gerenciar o schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

minio:
  endpoint: http://localhost:9000
  access.key: minio
  secret.key: minio123
  bucket.name: cursos-materiais